#!/usr/bin/env bash
#
# Clones the AWS CloudFormation documentation and searches it to find where
# the 'Tags' key is supported in a resource's schema. Prints the name of the
# resources.
#
# Fragile. If the docs formatting changes, this script may no longer work.
#

err() {
    >&2 echo "!!! $1"
    >&2 echo "    Exiting..."
    exit 1
}

git_url="https://github.com/awsdocs/aws-cloudformation-user-guide"
cd /tmp || err "Unable to cd to /tmp."
git clone "$git_url" cfn-docs
cd cfn-docs || err "Unable to cd to cfn-docs. Did git clone fail?"
grep '\[Tags\]' doc_source/* | cut -d : -f1 | sort -u | cut -d - -f3- | cut -d . -f1 | sort -u
cd
rm -rf /tmp/cfn-docs
